title: Shinwoo Kim
author: Shinwoo Kim
email: shinwookim@pitt.edu
description: >-
  I am a software developer based in Pittsburg PA USA who is interested in 
  computer architecture, distributed/operating systems, and compilers.
baseurl: "/~shk148"
url: "https://people.cs.pitt.edu"
twitter_username: _shinwookim
github_username: shinwookim
linkedin_username: kimshinwoo

collections:
  pages:
    output: true
    permalink: /:path/

markdown: kramdown
kramdown:
  highlighter: rouge
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

nav:
  - title: Home
    url: /
  - title: Projects
    url: /projects/
  - title: Teaching
    url: /teaching/
  - title: Contact
    url: /contact/

google_analytics: G-X43BZS6F4C
