title: Shinwoo Kim
author: Shinwoo Kim
email: shinwookim@pitt.edu
description: >-
  I am a software developer who is interested in computer architecture, 
  distributed and operating systems, and compilers.
baseurl: "/~shk148"
url: "https://sites.pitt.edu"
twitter_username: _shinwookim
github_username: shinwookim
linkedin_username: kimshinwoo

plugins:
  - jekyll-feed

include:
  - _pages

collections:
  pages:
    output: true
    permalink: /:path/

markdown: kramdown
kramdown:
  highlighter: rouge
  input: GFM
