name: Build Jekyll Site

on:
  workflow_call:
    inputs:
      require_npm:
        description: 'Require NPM'
        required: false
        default: false
        type: boolean
      repository: 
        description: 'Repository name'
        required: true
        type: string
      artifact_name:
        description: 'Artifact name'
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
      - if: ${{ inputs.require_npm }}
        name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - if: ${{ inputs.require_npm == true }}
        name: Install Node Dependencies
        run: npm install
      - run: ls
      - name: Build Site
        run: JEKYLL_ENV=production bundle exec jekyll build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: _site
