name: Check Links
on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
  workflow_dispatch:

jobs:
  build-site:
    name: Build Main Jekyll Site
    uses: "./.github/workflows/build-site.yml"
    with:
      repository: ${{ github.repository }}
      artifact_name: site
    secrets: inherit
  check-links:
    name: Check for Broken Links
    runs-on: ubuntu-latest
    needs: build-site
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: site
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1
        with:
          format: markdown
          fail: true
  